axone-protocol/axoned

.github/workflows/lint.yml, docs/static/openapi.yml
Fix the installed ignite cli version when checking generated sources.
To avoid any inconsistencies between local generation the CI generation, use the `--clear-cache` flag when proceeding locally to prevent `ignite` from checking sources checksums before generating the spec:
```sh
ignite generate openapi --yes --clear-cache
```
=> ci(lint): fix ignite version

.github/workflows/publish.yml
Fix the docker publication on the Docker Hub, login was done the the registry was missing in the image names.
=> ci(publish): explicitely reference docker hub as registry

README.md
Since @amimart has added a [guide for nodes & validators](https://docs.okp4.network/docs/nodes/introduction) to our documentation website, this PR just adds a section for validators with a link to that documentation.
=> docs: add section for validators

pkg/mint/okp4InflationCalculationFn.go, pkg/mint/okp4InflationCalculationFn_test.go
Fix the inflation calcul to provide an annual inflation rate, the per block being populated by the module itself.
Additionally, Staking rewards on the [Whitepaper](https://docs.okp4.network/docs/whitepaper/tokenomics#staking-rewards) being calculated once a year and the actual `mint` module calculating it every block there's a difference caused by previously minted coins. To mitigate this issue the initial inflation rate is set to 7.5% instead of 15%, but the distribution will not be linear across blocks, a re-implementation of the `mint` module shall be considered.
=> fix(mint): provide annual inflation rate

Dockerfile, Makefile, go.mod, go.sum
- Upgrade Ledger module to v0.9.3 to support latest Ledger model.
- Enable ledger support in binary.
Signed-off-by: dpierret <dapie@cros-nest.com>
=> Bump: ledger v0.9.3

docs/proto/logic.md, docs/proto/protodoc-markdown.tmpl, docs/proto/vesting.md
To make generated documentation compatible with docusaurus, we need to change the syntax of the comment used in the markdown template. Mdx doesn't support html comment ``. So replace to markdown comment `[//]: # (...)`.
[//]: # (Hey hey, you too you test this comment if it's work ? I didn't know too this syntax...)
[//]: # (🍍)
[//]: # (🍻)
=> Change comments syntax in markdown template

.github/workflows/notify-release.yml
Automatically trigger the docs repository on each new version released. 
Two workflows dispatch are triggered : 
- One for publish the new documentation version based on tag (See https://github.com/okp4/docs/pull/136 for more details)
- Another for update the latest version tag on configuration file (See https://github.com/okp4/docs/pull/134)
=> 📚 Trigger update docs repository

.github/workflows/test.yml
As tests start to take a while to run, this PR adds a mechanism to bypass tests when not needed.
=> ci(workflow): by pass blockchain test if not needed

.github/workflows/test.yml, Makefile, README.md
This PR adds the following targets to the makefile:
- `chain-init`: to initialize a chain in a local environment
- `chain-start`: to start the blockchain in a local environment
This is to simplify the testing of the blockchain in a local environment. In addition, the workflow `test` has been updated to support these new targets.
=> Add Makefile targets for initializing & starting chain

Makefile, buf.gen.doc.yaml, docs/proto/logic.md, docs/proto/mint.md, docs/proto/templates/default.yaml, docs/proto/templates/protodoc-markdown.tmpl, proto/logic/docs.yaml, proto/mint/docs.yaml
Generating documentation from protobuf files is wonderful but it's limited to the protobuf object structure. It could be nice to add more descriptions, explanations, example or more informations on each specific protobuf module documentation. This PR introduce a second templating system to add more information in each generated documentation. 
- All proto generation templates files have been moved into the `docs/proto/templates/*` folder. Two files is located inside : 
- `protodoc-markdown.tmpl`: is the markdown template for generating protobuf documentation with protoc-gen-doc.
- `default.yaml`: is the default variable used to insert into the protobuf documentation generated file. It could be override by each module. 
- `docs.yaml` is the file that will override variable defined into the …
=> 📚 Docs: improve proto docs by adding template variable

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/publish.yml
Publish protobuf file on [buf registry](https://buf.build/explore).
The lint process before the publish is already done on [lint workflow](https://github.com/okp4/okp4d/blob/main/.github/workflows/lint.yml#L121). 
Before merge, those steps is **mandatory** and can only be done by account holder. _This PR is kept in draft since those actions are not done._ 
https://docs.buf.build/tour/push-a-module
=> 📚 Publish proto on buf registry

x/logic/interpreter/registry.go, x/logic/predicate/bank.go, x/logic/predicate/bank_test.go, x/logic/predicate/util.go
In continuity of https://github.com/okp4/okp4d/pull/261, this PR implement the `bank_spendable_coins/2` predicate following #264 issue.
```prolog
bank_spendable_coins(?Account, ?Balances)
```
Where:
- `Account` represents the account address (in Bech32 format).
- `Balances` represents the balances of the account as a list of pairs of coin denomination and amount which are spendable (i.e. not locked).
```bash
$ okp4d query logic ask "bank_spendable_coins(X, Y)." --output json | jq
{                                                                                                                                                   
"height": "8042",
"gas_used": "14750",
"answer": {
"success": true,
"has_more": true,
"variables": [
"X",
"Y"
],
"results": [
{
"substitutions": [
{
"variable": "X", …
```
=> 🏦 Add spendable_coins predicate

x/logic/interpreter/registry.go, x/logic/predicate/bank.go, x/logic/predicate/bank_test.go, x/logic/predicate/util.go, x/logic/testutil/expected_keepers_mocks.go, x/logic/types/expected_keepers.go
In continuity of https://github.com/okp4/okp4d/pull/261, this PR implement the `bank_locked_coins/2` predicate following #263 issue.
```prolog
bank_locked_coins(?Account, ?Balances)
```
Where:
- `Account` represents the account address (in Bech32 format).
- `Balances` represents the balances of the account as a list of pairs of coin denomination and amount which are locked (i.e. not spendable).
```bash
$ okp4d query logic ask "bank_locked_coins(X, Y)." --output json | jq
{                                                                                                                                                   
"height": "8042",
"gas_used": "14750",
"answer": {
"success": true,
"has_more": true,
"variables": [
"X",
"Y"
],
"results": [
{
"substitutions": [
{
"variable": "X",
"term": …
```
=> 🏦 Feat: add bank_locked_coins predicate

x/logic/interpreter/registry.go, x/logic/predicate/bank.go, x/logic/predicate/bank_test.go
As mentioned [here](https://github.com/okp4/okp4d/pull/266#discussion_r1080974073), this PR is intended to rename the bank predicates to be consistent with the public [GRPC API](https://buf.build/cosmos/cosmos-sdk/docs/44fbb0df9cea049d588e76bf930177d777552cf3:cosmos.bank.v1beta1#cosmos.bank.v1beta1.Query.SpendableBalances). 
- rename `bank_spendable_coins/2` to `bank_spendable_balances/2`
- rename `bank_locked_coins/2` to `bank_locked_balances/2`
- Related discussion : https://github.com/okp4/okp4d/pull/266#discussion_r1080974073
- ⚠️ Waiting this PR before merge : #267
=> ✏️ Refactor: rename bank predicate

x/logic/keeper/grpc_query_ask.go, x/logic/keeper/interpreter.go
This is a proposal to fix an issue related to the presence of the bank & account keepers in prolog interpreter executions.
It ensures those keepers are present in the `sdk.Context` once unwrapped. It introduce an helper func `enhanceContext` to prepare the context before execution in which new elements may be added in the future.
=> fix(logic): ensure keepers in interpreter exec ctx

.github/workflows/test.yml, Makefile, README.md, app/app.go, app/upgrades.go, app/upgrades/v4/upgrade.go, x/logic/keeper/migrations.go, x/logic/migrations/v2/migrations.go, x/logic/module.go, x/logic/types/params.go
A PR to bring some functionalities to prepare upgrades of the chain.
Add necessary upgrade handlers to prepare chain upgrade and migration.
The logic module introduce new params and remove the foo/bar params. A migration has been configured to set the new params with its defaults values. Logic modules consensus version has been incremented to v2. A migration folder structure has been set with its related migration. 
A new make command has been added to test chain upgrade : 
```bash
make chain-upgrade FROM_VERSION=v3.0.0 TO_VERSION=v4.0.0   
```
This command will build the current go project, download the old version from GitHub tag `FROM_VERSION`, build and start this version with cosmovisor. Vote proposal will be submitted and voted to make an upgrade after 10 block. Then the new binary …
=> ⬆️ Prepare upgrade handlers

x/logic/interpreter/registry.go, x/logic/predicate/address.go, x/logic/predicate/address_test.go
In the `logic` module, purpose an utility function to manipulate bech32 address. 
`bech32_address/2` is a predicate that convert a bech32 encoded string into base64 bytes and give the address prefix or convert a prefix and base64 encoded bytes to bech32 encoded string. The signature is as follow:
```prolog
bech32_address(-Address, +Bech32)
bech32_address(+Address, -Bech32)
bech32_address(+Address, +Bech32)
```
Where:
- `Address` is a pair containing HRP (Human-Readable Part) containing the address prefix and the list of integers between 0 and 255 (byte) that represent the base64 encoded bech32 address string. Represented like this : `-(HRP, Address)`
- `Bech32` is an Atom or string representing the bech32 encoded string address 
```
bech32_address(-(Hrp, Address), …
```
=> 🧠 Logic: 📪 `bech32_address/2` predicate

app/upgrades.go, app/upgrades/v41/upgrade.go
For the next coming release, this PR add the update handler o the chain. This handler will do not execute migration since there is no migration for this release. 
This update has been successfully tested (with an empty chain) with this command tool : 
```cli
make chain-upgrade FROM_VERSION=v4.0.0 TO_VERSION=v4.1.0
```
New predicates introduced in this release are working ;)
=> Chore: ⬆️ prepare handler for 4.1.0 upgrade

Makefile
Self explanatory. Fixes `make clean chain-init` call.
=> build(project): add build dependency to chain-init

go.mod, go.sum, x/logic/keeper/grpc_query_ask.go, x/logic/keeper/interpreter.go, x/logic/meter/safe.go, x/logic/predicate/address_test.go
When prolog executing query through the logic `Ask` gRPC query, the prolog predicates are executed in a separate goroutine. In case this goroutine panic we are not able to recover from it, so the https://github.com/okp4/okp4d/pull/312 introduced a change in the gas consumption handling, making the goroutine stop instead of panic. This works on async parts, but may be problematic on synchronous parts.
Since https://github.com/ichiban/prolog/pull/290 released in the [v1.1.0 version](https://github.com/ichiban/prolog/releases/tag/v1.1.0) any panics occurring while executing predicates are recovered and an error is returned back to the interpreter client through the `Solutions.Err()` func. The panic being recovered, this PR adds a check on gas consumption to panic again with the …
=> Fix logic async gas consumption

Makefile, app/upgrades.go, app/upgrades/v5/upgrade.go
This PR follow #282 to apply all necessary migrations since new feature development on the logic module, and for the update of cosmos-sdk from 0.46.6 to 0.47.1.
=> ⬆️ Upgrade handler v5 for cosmos v0.47.1

.github/workflows/notify-release.yml, .github/workflows/update-draft-docs.yml
Self explanatory. Fixes naming of `notify-release` and `update-draft-docs` names.
=> ci(workflow): fix workflow naming

Makefile, x/logic/keeper/grpc_query_ask_test.go, x/logic/keeper/grpc_query_params_test.go, x/logic/keeper/msg_server_test.go, x/logic/types/params.go, x/logic/types/params_test.go
Add basic tests on common module files on the `logic` module that wasn't covered by unit test. 
To follow `Interpreter` params design, I've introduce [options](https://github.com/okp4/okp4d/pull/335/files#diff-760778a5bc6310e2c70e632f9a0df2e5662d35561bd28a73ed9c3e81fecff80bR120) for instantiate `Limits` params.
=> 🧪 Add more tests on logic module

Dockerfile, x/logic/interpreter/registry.go, x/logic/predicate/json.go, x/logic/predicate/json_test.go, x/logic/predicate/util.go, x/logic/predicate/util_test.go
This PR implement #348.
I hope tests case will cover all needs and json specification. 
On this implementation, decimal number is not handled now. It will be the part of another PR.
=> 🧠 Logic: 🧱 implement `json_prolog/2`

x/logic/interpreter/registry.go, x/logic/predicate/uri.go, x/logic/predicate/uri_test.go
This PR implement #352.
Implementation has been more complicated than expected since [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) is not followed same on SWI-Prolog and Golang `net/url` implementation. 
I took the initiative to exactly follow the behavior of `SWI-Prolog`, which involved rewriting the escaping implementation. See in code comment for more explanation : https://github.com/okp4/okp4d/pull/355/files#diff-ee2d93b65d420c2dc3609a71543f8a871b44d84ea108dd36580a016d97676abdR38
=> 🧠 Logic: 🔗 implement `uri_encoded/3`

app/upgrades/v5/upgrade.go
#368 [fail with this `//nolint staticcheck`](https://github.com/okp4/okp4d/actions/runs/5159578056/jobs/9323426905) and when merging it, this is fail without, I didn't understand why but this PR re-introduce it and linter is now happy.
=> fix(lint): add nolint for deprecated func in migration

x/logic/keeper/grpc_query_ask_test.go, x/logic/keeper/interpreter.go
When there is an error when asking logic module, module return a valid answer but with the `success` boolean set to `false`. This answer attribute (`success`) is only intended to say that the question your asking is not successful (there is no answer possible) but it doesn't mean that the interpreter fails. 
Now, when a error occurs in the prolog program, the error is now returned as an RPC error and command fails.
```bash
❯ okp4d query logic ask "json_prolog(Json, Term)."
answer 
has_more: false
results: []
success: false
variables: []
gas_used: "2216"
height: "136124"
user_output: ""
```
```bash
❯ okp4d query logic ask "json_prolog(Json, Term)."
Error: rpc error: code = InvalidArgument desc = error interpreting solutions: json_prolog/2: could not unify two variable: invalid argument: …
```
=> 🧠 Logic: return RPC error on interpreter error

x/logic/predicate/did_test.go, x/logic/util/prolog.go
A potential issue was found (thanks @antho31) when asking the prolog interpreter to unify a string representing a did uri to DID component atom. When trying to unify `did_components('did:example:123456?versionId=1', did(Method, ID, Path, Query, Fragment)).` Where `did:example:123456/test?versionId=1'` doesn't contains either a `Path` or a `Fragment`, those two atom are unified to a new variable because it's represented as an empty string. The result substitution will give something like this : 
```json
{
"variable": "Fragment",
"term": {
"name": "_210",
"arguments": []
}
},
{
"variable": "Path",
"term": {
"name": "_282",
"arguments": []
}
},
```
In the ichiban core interpreter, NewVariable is represented with an int64 and incremented each time its call but incremental value is kept in the …
=> 🧠 Logic: fix empty string conversion to Atom

.github/workflows/lint.yml
The [golangci-lint-action](https://github.com/golangci/golangci-lint-action) seems to encounter cache issues sometimes, see: https://github.com/okp4/okp4d/actions/runs/5320225585/jobs/9636440668
This is related to this issue: https://github.com/golangci/golangci-lint-action/issues/135
It seems that disabling the `setup-go` action cache solves that, it shouldn't be problematic as the golangci action has its own cache.
=> ci(lint): prevent golangci cache issues

x/logic/fs/wasm.go, x/logic/fs/wasm_test.go
=> 🧠 Logic: 🐛 Fix `consult/1` base64 decoding 

x/logic/interpreter/registry.go, x/logic/predicate/string.go, x/logic/predicate/string_test.go, x/logic/testutil/logic.go
=> 🧠 Logic: ⛓️ Implement `read_string/3` predicate

x/logic/interpreter/registry.go, x/logic/predicate/file.go, x/logic/predicate/file_test.go, x/logic/testutil/logic.go
Implement our own `open/4` predicate, allowing usage of the virtual file system to open wasm uri which was not used in the ichiban implementation. 
See #379 for more details.
=> 🧠 Logic: `open/4` predicate

.github/workflows/publish.yml
Since tag option is [not handled](https://github.com/bufbuild/buf-push-action/issues/20) by the GitHub Buf action, I replace the action by the classic cli command. It will push the released proto when tags is pushed, otherwise it will push as draft on Buf registry.
=> 🧬 Publish draft and tagged Buf proto on registry

.github/workflows/publish.yml
Sorry for the second PR following #408, [draft is not allowed on main branch](https://github.com/okp4/okp4d/actions/runs/5423718329/jobs/9862063062#step:4:7) (since `main` name isn't allowed by buf registry). Put back like is [done on the buf-push-action](https://github.com/bufbuild/buf-push-action/blob/main/push.bash#L40) except that in case of a tag, we put the tag name instead of the commit SHA.
=> 🧬 Buf: don't draft on main

app/app.go
IBC relayers seems to fail cuz of store key missing.
Works with Hermes relayer
=> ibcfee fix

.github/workflows/lint.yml
Self explanatory. This PR introduces a basic Github Action job into the existing `lint` workflow for CodeQL. This job assesses general security and code quality to enhance and improve the overall quality of the code of the chain.
=> ci(workflow): add codeql analysis job on go source

.github/workflows/notify-release.yml
Fix [the job](https://github.com/axone-protocol/axoned/actions/runs/9178689492/job/25239152908) that notify [axone-protocol/docs](https://github.com/axone-protocol/docs) repository when a new version of [axoned](https://github.com/axone-protocol/releases) is release. 
I don't know why but the workflow id was incorrect, I guess is the migration from okp4 organisation but it's strange since the other workflow ID didn't changes.
=> 🐛 ci: fix notify version bump on docs

.github/workflows/notify-release.yml
Continuing from the previous release failure, we encountered another issue related to the [synchronization failure](https://github.com/axone-protocol/docs/actions/runs/9178693387/job/25239171883) between the `axoned` repository and the `docs` repository. This issue was caused by an incorrect path name for the predicates documentation.
=> 🐛 ci: fix incorrect folder name for update predicate docs

Makefile
=> build(project): update -tags format to use comma-separated values
